### ISSUE TITLE
Compile CPython

### ISSUE THREAD

**Issue by MaxNoe** [ShivamSarodia/ShivyC#41]
That would be kinda awesome!

**Comment by ShivamSarodia** [comment]
Hi MaxNoe, thanks for the suggestion! Unfortunately, compiling CPython is quite a bit beyond the capabilities of ShivyC today, but it is certainly an awesome long-term target.

**Comment by ShivamSarodia** [comment]
Closing for now as too far ahead in the roadmap - will reopen when this is more feasible.
