### ISSUE TITLE
Suggestion to use ppci as an assembly backend 

### ISSUE THREAD

**Issue by windelbouwman** [ShivamSarodia/ShivyC#55]
Hi,

Very cool project! It is very well feasible to write a C compiler in python. My own attempt is over here: http://ppci.readthedocs.io . Maybe you can use parts of it to generate binaries and ELF executables. Btw, the ppci project also contains a C compiler, so this is duplicate of the shivyc project. I will certainly check out how you did it.

Regards,
Windel

**Comment by ShivamSarodia** [comment]
Hi Windel, thanks for reaching out! I haven't seen ppci before so I'm really eager to take a look :)

For now, I'd like to keep ShivyC dependency free. But I'll definitely look over the ppci source code when I get a chance to see what techniques from ppci can improve ShivyC.

**Comment by windelbouwman** [comment]
Hi Shivam! I think it is a very good idea to keep shivyc dependency free (ppci has exactly that same goal, actually the projects are remarkable similar), but now it also depends on binutils. I might be better to depend upon an assembler which can be installed via pip, like peachpy (https://github.com/Maratyszcza/PeachPy).

You might also be interested in this list of similar projects I found: http://ppci.readthedocs.io/en/latest/reference/links.html I will add shivyc to this list.
